# Permalinks
permalink:           pretty

# Setup
title:               unistAR
tagline:             UNIST Capstone Design 2018 - AR input device
url:                 https://unist-ar.github.io
baseurl:             ""
analytics_id:

# Owner/author information
owner:
  name:           unistAR
  location:       "Ulsan, KR"
  year:           2018


# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
